### PR TITLE
Adding UsableNet

### PR DESCRIPTION
**Pull request by aardrian**

### CODE REVIEW

**Comment by aardrian** [comment]
For some context, here is some evidence why I believe UsableNet (and specifically its "Assistive" offering) should be added.

1. Implies WCAG conformance requires no effort, [that its tooling can do it](https://usablenet.com/technology/assistive-technology-services#:~:text=Our%20Assistive%20platform%20offers%20an%20end%2Dto%2Dend%20solution%20that%20dynamically%20remediates%20and%20maintains%20the%20accessibility%20of%20your%20site%20so%20it%20conforms%20to%20the%20most%20current%20standards.):

> Our Assistive platform offers an end-to-end solution that dynamically remediates and maintains the accessibility of your site so it conforms to the most current standards.

2. We already know "ADA compliance" is not a thing, but here it is as a [marketing promise](https://usablenet.com/technology/assistive-technology-services#:~:text=We%20deliver%20a%20fully%20ADA%2Dcompliant%20site%20tested%20with%20automated%20tools%2C%20manual%20review%20and%20people%20from%20the%20disability%20community.):

> We deliver a fully ADA-compliant site tested with automated tools, manual review and people from the disability community.

3. [Promises WCAG conformance](https://usablenet.com/technology/assistive-technology-services#:~:text=Our%20work%20ensures%20your%20site%20conforms%20fully%20to%20the%20highest%20standards%20(WCAG%202.0%20or%202.1%20AA).) (which I disprove later):

> Our work ensures your site conforms fully to the highest standards [(WCAG 2.0 or 2.1 AA)](https://blog.usablenet.com/new-web-content-accessibility-guidelines-wcag-2.1-what-when-how).

4. Relies on automated captions for its [marketing videos](https://www.youtube.com/watch?v=oOtLTtnInBM), without correcting them:
   - The URL shown in the captions is mptv.org instead of UsableNet.
   - Captions refer to ADA as a DA, two separate words (article and DA).
   - Promises of WCAG 2.0 conformance in run-on sentences with no punctuation.

5. Pitches a de facto one-click solution through its "Enable accessibility" add-on at customer sites:

   - An arrow pointing out the one-click control on a site, with the text: Enable Accessibility with UsableNet's Web Accessibility Software Solution. No matter how big or small your business, Assistive provides an accessibility solution for desktop and mobile- all within a matter of weeks.

6. Uses an add-on which does not work unless you enable third-party cookies:

   - Browser alert: an embedded page at a40.usablenet.com says, Your web browser privacy settings are preventing the accessibility mode to stay enabled. Try enabling third party cookies to ensure you receive accessible updates to the website.

7. Generates more than twice as many automated test warnings with TPGi's ARC Toolkit when enabled ([DSW home page](https://www.dsw.com/en/us/)).

   - With UsableNet's add-on disabled: 21 ARC errors and 29 warnings.
   - With UsableNet's add-on enabled: 15 ARC errors and 71 warnings.

8. Generates more issues in Deque's Axe when enabled ([DSW home page](https://www.dsw.com/en/us/)).

   - With UsableNet's add-on disabled: 46 total Axe issues, 10 needing review.
   - With UsableNet's add-on enabled: 47 total Axe issues, 14 needing review.


Anything requiring me to use CPU cycles on my computer to remediate code on every visit while also self-identifying a disability to un-break a site is an overlay to me. It is not an equal experience. It also presents a false choice between privacy/security and accessibility.

Not all overlays need to present a bevy of widgets that adjust content in nonsense ways or just fail to work, some can just fail silently.

**Comment by karlgroves** [comment]
@aardrian do you think it would be worthwhile to specify the actual product?
This is more of a grey area with UsableNet than AccessiBe (or is it?).

UsableNet used to make those "alternate" versions of customers' sites. [Those were mostly crap](https://karlgroves.com/2015/11/13/when-the-treatment-is-worse-than-the-disease), but AFAIK they've stopped doing that.

However, now there's this "UsableNet Assistive".

Do we know if UsableNet has any other offerings? Is this used in conjunction with services or is it stand alone?

Your evidence above is already pretty solid. I just wonder if, in context of this PR, its worth clarifying the product name

**Comment by aardrian** [comment]
@karlgroves Fair point. The issues I cite are primarily around that specific product offering. And, unlike accessiBe or UserWay or others, UsableNet started not as a product but as a service offering (as you note). And UsableNet has other products, meaning "UsableNet" alone is not synonymous with its overlay product.

I amended my PR to name the product.

**Comment by aardrian** [comment]
When does this show up on the live site?

**Comment by lonnyobrien** [comment]
### Clarification needed on UsableNet Assistive and Accessibility for Ontarians with Disabilities Act, 2005 (AODA) Conformance Claims

Good evening Jason,
I'm hoping you can clarify UsableNet Assistive and Accessibility for Ontarians with Disabilities Act, 2005 (AODA) conformance claims on your website?

UsableNet Assistive claims on its website to continously achieve Accessibility for Ontarians with Disabilities Act, 2005 (AODA) compliance with each new release and code change. 

### Screenshot

Web Accessibility Solutions, Digital  WCAG Accessibility Solutions  UsableNet, Inc. screen shot of AODA claims. With each new release and code change, Assistive keeps you in compliance with WCAG and access laws like the Americans with Disabilities Act (ADA) and **the Accessibility for Ontarians with Disabilities Act (AODA)

### Text excerpt from UsableNet website

**A Complete Web Accessibility Solution**

UsableNet Assistive enables accessibility on your website in weeks and provides the most WCAG compliant and usable experience for people with disabilities. Unlike a widget, our accessibility experts work for you, testing, performing accessibility remediation, and helping your site stay ADA compliant.

With each new release and code change, Assistive keeps you in compliance with WCAG and access laws like the Americans with Disabilities Act (ADA) and **the Accessibility for Ontarians with Disabilities Act (AODA)**. Watch the video

Source: UsableNet website https://usablenet.com/technology/assistive-technology-services

- AODA's scope contains integrated standards far beyond a website's conformance to Web Content Accessibility Guidelines. For example: How does your solution meet the legal requirements and needs of a disabled individual that asks for website content to be made available to them in an alternate accessible format (such as large print, mp3, transcript, braille, captions, etc.)? Specifically, how does UsableNet developers, testers and third-party providers work on behalf of the business with disabled individuals to meet the Ontario Human Rights Legislation, the Canadian Charter of Rights and Freedoms and additional relevant legislation? 
- AODA legally requires that businesses and non-profits with 20 or more employees file accessibility compliance reports. It is an offence to provide false or misleading information in an accessibility report and corporations can be fined $100,000 each day or part of a day on which the offence occurs or continues to occur. Source: [website] https://www.ontario.ca/laws/statute/05a11#BK17 How do you confirm your claims of AODA conformance in weeks will be sufficient to avoid fines and when the Ministry for Seniors and Accessibility and the Government of Ontario do not endorse or recommend any accessibility consultant(s), their advice, opinions or recommendations. Source: Disclaimer [website] https://www.ontario.ca/page/accessibility-in-ontario 
- In addition, It is becoming more common for organizations to do a risk assessment and request a VPAT 2.4Rev INT (March 2022). Are you able to provide these documents?

I look forward to reading your response and for your time.

Best regards,
Lonny O'Brien

**Comment by aardrian** [comment]
Trying to address this in chunks (I am independent, so filing and responding to PRs is unpaid labor), and will address the more straightforward one first.

> First, I address how the UsableNet Assistive service works and why Assistive does not fit the definition on the Overlay Fact Sheet.   

If we are restricting ourselves solely to the [definition on OFS](https://overlayfactsheet.com/#what-is-a-web-accessibility-overlay), then here it is: "**Overlays are a broad term for technologies that aim to improve the accessibility of a website. They apply third-party source code (typically JavaScript) to make improvements to the front-end code of the website.**"

> UsableNet Assistive Service is not a mass market product, as all the other tools listed on the Overlay Fact Sheet.

That is not part of the definition.

> The Platform aspect of UsableNet Assistive manages the remediation code. The website remediations get applied to the website once the ‘Enable Accessibility’ link is selected. The process is on-the-fly; it is not a separate website; it is 100% dynamic (much the same as every website has a dynamic desktop and mobile rendering of the same site).

That tells me it uses _third-party code_ ("Assistive manages the remediation code") to make _improvements to the front-end code_ of the site after it has been delivered/rendered ("process is on-the-fly").

(As a point of fact for the parenthetical statement, not every web site has "dynamic desktop and mobile rendering"; OFS does not, for example.)

As far as I see, UsableNet Assistive meets the definition of _overlay_ as provided on this site.

**Comment by karlgroves** [comment]
Please shift any comments to https://github.com/karlgroves/overlayfactsheet/issues/957

**Comment by UsableNet-WCAG** [comment]
understand the discussion has moved to another ticket. Wanted to make sure @lonnyobrien got a response. I believe a address @aardrian website claim observations in my response above. lease Adrian let me know if I did not.

Hi Lonny

The UsableNet Assistive Service is one of a number of approaches we offer. In all client engagements, it would most likely be provided , as part of an overall package of services to match the clients challenges. The fast majority of our clients do not use the UsableNet Assistive Service, we support them with other more traditional type support for internal accessibility efforts. 

The description of UsableNet Assistive Service is focused on addressing the web experience in he context of any legal obligation. We do not sell it as a stand alone tool or solution to solve , in most cases, a range of accessibility client needs - we careful work with clients to build out a range of services if needed. We do provide VPAT, we also provide training courses, Audits, Testing platform and many other approaches that can be mixed to the client need. I have asked the team to tweak the wording on the page you identified to ensure its clear that UsableNet Assistive Service is to help with the web experience component of a clients need.

**Comment by lonnyobrien** [comment]
Thanks for the clarification and quick response.

**Pull request merged**
