### PR TITLE
Use grid for quotes, add landmark regions

### PR DESCRIPTION
**Pull request by ericwbailey**
This PR:

- Links directly to the endorse subsection in the README from the "Add your name to this list" link
- Makes the "Add your name to this list" link more visually prominent
- Adds document landmarks
- Adds a grid for "in their own words" quotes

A 3 column grid of quotes from the Overlay Fact Sheet website.

### CODE REVIEW

**Comment by karlgroves** [comment]
@ericwbailey Merge conflicts.  :-(

**Comment by ericwbailey** [comment]
@karlgroves Should be good now. Nice to see more signatures on the list.

**Comment by karlgroves** [comment]
@ericwbailey conflicts again. Sorry.  :-(

**Comment by ericwbailey** [comment]
@karlgroves Back to you!

**Pull request merged**
