### PR TITLE
Add privacy section

### LINKED ISSUE #5: Screen reader detection
At least one tool of this kind detects if a screen reader is running, and automatically invokes certain options within its overlay without asking.

If it is known that someone is using a screen reader, it is known that they have a disability. That is personal data, and there are laws that prohibit the collection and use of personal data without informed consent.

I've reached out to friends who specialise in privacy for their thoughts.

### PR DESCRIPTION
**Pull request by karlgroves**
Resolves #5

### CODE REVIEW

**Comment by LJWatson** [comment]
Until there is more data about overlays using cookies to track users, that part can't be verified. At least one of the worst offenders does not seem to use cookies to track users - no persistent data is stored in their cookies at any rate.

What we do know is that these overlays track users on the websites they're enabled on (by "tracking clicks and heatmaps" according to one vendor), and that the scripts that do this are loaded from the vendor's servers. So that, in addition to browser fingerprinting, overlay companies have a centralised way to track users across websites that use their overlays without needing to use cookies at all.

**Comment by Aircl0wn** [comment]
> Until there is more data about overlays using cookies to track users, that part can't be verified. At least one of the worst offenders does not seem to use cookies to track users - no persistent data is stored in their cookies at any rate.
> 
> What we do know is that these overlays track users on the websites they're enabled on (by "tracking clicks and heatmaps" according to one vendor), and that the scripts that do this are loaded from the vendor's servers. So that, in addition to browser fingerprinting, overlay companies have a centralised way to track users across websites that use their overlays without needing to use cookies at all.

Let's put on a darker hat..
It's not only about the overlay provider potentially using this data.
Any tracker could add code that fingerprints someone that interacts with a known overlay (or general code sample to i.e. increase font-size).

**Comment by LJWatson** [comment]
> Let's put on a darker hat..
> It's not only about the overlay provider potentially using this data.
Any tracker could add code that fingerprints someone that interacts with a known overlay (or general code sample to i.e. increase font-size).

Yes, they could, but that is not unique to overlays. The same is true for legitimate scripts that provide accessibility - like the greasemonkey scripts provided by NVAccess for example.

Unless there is evidence that overlays are being hijacked in this way, then it is speculative at best - and that risks undermining the credibility of this "non-biased, community-driven, fact-based information sheet".

**Comment by karlgroves** [comment]
Closing in deference to an updated PR

**Pull request closed without merging**
