### PR TITLE
Add people

### PR DESCRIPTION
**Pull request by accessiblewebadmin**

### CODE REVIEW

**Comment by karlgroves** [comment]
@accessiblewebadmin I appreciate the support, but can you get each of those people to send me an email (or comment here) that they want to be added?

**Comment by petebruhn** [comment]
Please add me! Thanks!

**Comment by nicoalli** [comment]
please add me to the list! thank you!

**Comment by smccracken** [comment]
Please add me to the list. Thank you!

**Comment by alaina-a11y** [comment]
I would like to be added, thank you!

**Pull request merged**
