### PR TITLE
Adds privacy section

### PR DESCRIPTION
**Pull request by LJWatson**
Adds a privacy section per #5

### CODE REVIEW

**Comment by LJWatson** [comment]
I thought about adding a link to the post I wrote about [screen reader detection](https://tink.uk/thoughts-on-screen-reader-detection/), but didn't want to dilute the focus on overlays. @karlgroves  feel free to add it in or let me know if you think otherwise.

**Comment by karlgroves** [comment]
@LJWatson Is there any information out there that describes how that detection works?  

Another aspect that I think is related, is that the overlay company may set a cookie on the user's browser that's then shared elsewhere (i.e. on other sites that use the overlay).  So if you select to use an overlay feature on one site, the overlay will automatically turn on that feature on other sites.

While the overlay company might think they're doing good by the end user, the big privacy problem is that the user never opted in to be tracked and there's also no ability to opt-out.   Seriously bad for GDPR and CCPA

**Comment by LJWatson** [comment]
> Is there any information out there that describes how that detection works?

It's been discussed in different places (email threads, Github issues and the like), but I don't know of a particularly authorotative source I'm afraid.

> Another aspect that I think is related, is that the overlay company may set a cookie on the user's browser that's then shared elsewhere (i.e. on other sites that use the overlay). So if you select to use an overlay feature on one site, the overlay will automatically turn on that feature on other sites.
>
> While the overlay company might think they're doing good by the end user, the big privacy problem is that the user never opted in to be tracked and there's
also no ability to opt-out. Seriously bad for GDPR and CCPA

Agreed. I don't know if this happens though, or how you'd test for it come to think of it.

Interestingly it seems that at least one of these overlays is blocked by Firefox when Enhanced Tracking Protection (ETP) is enabled.

**Comment by karlgroves** [comment]
Closing. Superseded by PR #221 

The original PR by @LJWatson  was out of date, but GH oddly didn't have away to update.

**Pull request closed without merging**
